//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace keybon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string portName {
            get {
                return ((string)(this["portName"]));
            }
            set {
                this["portName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout1 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout1"]));
            }
            set {
                this["Layout1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout2 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout2"]));
            }
            set {
                this["Layout2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout3 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout3"]));
            }
            set {
                this["Layout3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout4 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout4"]));
            }
            set {
                this["Layout4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout5 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout5"]));
            }
            set {
                this["Layout5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout6 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout6"]));
            }
            set {
                this["Layout6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::keybon.ScreenLayout Layout7 {
            get {
                return ((global::keybon.ScreenLayout)(this["Layout7"]));
            }
            set {
                this["Layout7"] = value;
            }
        }
    }
}
